### ISSUE TITLE
No access to /dev directory

### ISSUE THREAD

**Issue by gliargovas** [binpash/try#13]
It would be nice if we were able to mount the `/dev` directory to the overlay as well. Currently, this fails, and as a result commands that write to `/dev/null` are doomed to fail.

```
$ try git clone https://github.com/binpash/try.git
mount: /tmp/tmp.Q15MleyJXP/temproot/boot: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
mount: /tmp/tmp.Q15MleyJXP/temproot/var: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
fatal: could not open '/dev/null' for reading and writing: No such file or directory
```

**Comment by angelhof** [comment]
This is due to not making an overlay for `/dev/` (https://github.com/binpash/try/blob/main/try#L33). However, when I try to remove `dev` from excluded dirs, the following error is returned:
```sh
mount: /tmp/tmp.6dlCPc8bZQ/temproot/dev: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
```

We need to figure out why overlay on `/dev` fails.
