### ISSUE TITLE
try not preserving env vars

### ISSUE THREAD

**Issue by ezrizhu** [binpash/try#144]
eric in ide0 in ~ 
λ try echo a      
a

eric in ide0 in ~ 
λ try export abc=123

eric in ide0 in ~ 
λ echo $abc

**Comment by ezrizhu** [comment]
@mgree is this intended or should we work on fixing this

**Comment by angelhof** [comment]
It is expected! Since we run this export in a subshell there is no way to export them out of try. I think we should close it.
