### ISSUE TITLE
Potential issue with `rename` system call

### ISSUE THREAD

**Issue by SleepyMug** [binpash/try#170]
If the command being run has `rename` in it, while the renaming target is an existing directory, `try` gives EXDEV (Invalid cross-device link)

Potentially related to redirect_dir feature (https://docs.kernel.org/filesystems/overlayfs.html#renaming-directories)

To recreate:

Create `rename.c`:
```
#include <stdio.h>
#include <unistd.h>

int main(void)
{
    int ret;
    ret = link("x", "y");
    printf("link ret=%d\n", ret);
    ret = unlink("x");
    printf("unlink ret=%d\n", ret);
}
```

Then do the following:
```
$ gcc rename.c -o rename
$ mkdir x
$ ./rename
rename: Success
$ rmdir y; mkdir x
$ try ./rename
rename: Invalid cross-device link
```

**Comment by kwakubiney** [comment]
Can i pick this up? Assign to me if possible :)

**Comment by ezrizhu** [comment]
> Can i pick this up? Assign to me if possible :)

Sure thing, please make a PR when it's ready.

**Comment by kwakubiney** [comment]
Which environment did you run the `rename` binary on? @SleepyMug

**Comment by SleepyMug** [comment]
Sorry for the late reply. I think the key here is that `x/` and `y/` lives on a different FS as `/tmp`.

For some reason I could not recreate the problem with `link` anymore, but `rename` does trigger the issue.

```
#include <stdio.h>
#include <unistd.h>

int main(void)
{
    int ret;
    ret = rename("x", "y");
    if (ret < 0) {
        perror("rename");
    }
}

```
This is the kernel config in case it's useful.
```
$ grep /boot/config-$(uname -r) -e 'OVERLAY'
CONFIG_EFI_CUSTOM_SSDT_OVERLAYS=y
CONFIG_OVERLAY_FS=m
# CONFIG_OVERLAY_FS_REDIRECT_DIR is not set
CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y
# CONFIG_OVERLAY_FS_INDEX is not set
CONFIG_OVERLAY_FS_XINO_AUTO=y
# CONFIG_OVERLAY_FS_METACOPY is not set
```

**Comment by mgree** [comment]
Closing this as WONTFIX. This is an applicaiton-level issue and there's nothing we can do to fix broken applications.

**Comment by kwakubiney** [comment]
I've been thinking about this, and doesn't `try` sort of guarantee that whatever outcome you'd get on your machine without `try` would be the same you'd get on `try`? The usage of overlays is an implementation detail the user shouldn't really care about or?
