### ISSUE TITLE
README (possible) missing required package

### ISSUE THREAD

**Issue by vagos** [binpash/try#176]
When using OrbStack to start a container, `try` fails even after having all required packages installed. 
Turns out, installing the `unionfs-fuse` package fixes this issue. 

Solution: Add `unionfs-fuse` (or equivalent) to the README instructions.

**Comment by ezrizhu** [comment]
https://github.com/binpash/try/blob/71cb5699aae8b27b0347de5e5ebf234e402e90a3/README.md?plain=1#L31

**Comment by vagos** [comment]
Ah yes! Can we make these two packages also bullet-points? Right now it's a little hard to see when scanning the repo. Your call though.

**Comment by ezrizhu** [comment]
> Ah yes! Can we make these two packages also bullet-points? Right now it's a little hard to see when scanning the repo. Your call though.

Good point, I'll add that to the todo list.
