### ISSUE TITLE
Consistency: proper user id

### ISSUE THREAD

**Issue by ericzty** [binpash/try#24]
When we're first in unshare, we are mapped to the root user so that we can mount the directories.
But that is not the actual uid of the caller user, does this matter?
We could use another unshare to map the user id back.

**Comment by ericzty** [comment]
In the fix-gid branch, the groups are mapped one to one.

**Comment by mgree** [comment]
I think `fix-gids` and one-to-one mapping is just the way to go.

**Comment by ericzty** [comment]
On Sat Jun 24, 2023 at 11:20 AM EDT, Michael Greenberg wrote:
> I think `fix-gids` and one-to-one mapping is just the way to go.

With `sudo` in the future branch, all users and group ids are mapped
one-to-one.
