### ISSUE TITLE
Distro Compatibility

### ISSUE THREAD

**Issue by ericzty** [binpash/try#28]
Works on Ubuntu 20.04.6 `5.4.0-152-generic`
Works on Ubuntu 23.04 `6.2.0-23-generic`
Works on Rocky 9 `5.14.0-284.11.1.el9_2`
Works on Centos 9 Stream `5.14.0-325.el9`
Works on Debian 12 `6.1.0-9-amd64`

Fails on Debian 10 `5.10.0-21-amd64`
Fails on Debian 10 `4.19.0-24-amd64`
Fails on Debian 11 `5.10.0-23-amd64`
Fails on Centos 7 `3.10.0-1160.90.1.el7`
Fails on Centos 8 Stream `4.18.0-496.el8`

Note: systems where unprivileged userns is disabled by default (e.g., debian 10) we can run `sysctl -w kernel.unprivileged_userns_clone=1` to let unshare --user work.

**Comment by ericzty** [comment]
Changed the repo on the Debian 11 machine to `testing`, upgraded Linux to `6.1.0-9-amd64`, seems to have fixed it.

**Comment by ericzty** [comment]
Fails on Centos 8 Stream `4.18.0-496.el8`

**Comment by ericzty** [comment]
Fails on alpine and arch where /tmp is tmpfs, so the inner unshare could not see the temp script to execute.

**Comment by angelhof** [comment]
Thanks a lot Eric! Could we add some of the different passing distros in CI? That would be great to guard against regressions
