### ISSUE TITLE
Suggestion for See Also: checkinstall

### ISSUE THREAD

**Issue by alphapapa** [binpash/try#49]
This looks like a nice tool.  Thanks for sharing it.

You may not be aware of an old tool named `checkinstall`, which works similarly: changes to the filesystem are intercepted, they are collected into a distro-specific package, and installed with the distro's package manager; then the package can be removed to undo the changes.  It's been available in Debian, Red Hat, etc. for a long time.

It would be good to mention it in the readme as an alternative: http://checkinstall.izto.org/

**Comment by DivyanshuBist** [comment]
Hi,Can I take this issue?
I think updating try.1.md  ```See also``` section with  ```check install``` url would we enough

**Comment by ericzty** [comment]
Sure go ahead!
Thanks.
