### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by Trung0246** [binpash/try#57]
Currently FreeBSD missing `unshare` and maybe other unaddressed issues?

**Comment by ericzty** [comment]
From some initial googling, it does not seem like FreeBSD has overlayfs or unshare. Although there is unionfs and jail.

**Comment by angelhof** [comment]
Closing this issue for now since unshare and overlayfs are not supported on FreeBSD. If someone wants to implement a different version of try with unionfs/jail we could reopen this issue.
