### ISSUE TITLE
Offer also for macOS?

### ISSUE THREAD

**Issue by MichaelVoelkel** [binpash/try#59]
Would be cool if it also worked for macOS. I just downloaded and tried to run but obviously this cannot work without tools like unshare :)

**Comment by eiiot** [comment]
Homebrew would be ideal!

**Comment by JanPokorny** [comment]
Might not be possible to imlement: https://unix.stackexchange.com/questions/504030/macoss-counterpart-to-linuxs-unshare2

**Comment by mgree** [comment]
It is definitely not possible using our current approach: macOS doesn't have unshare or namespaces. By way of comparison, Docker on macOS is a VM.

If you know the macOS APIs well and want to chat, we'd be happy to.

**Comment by angelhof** [comment]
Closing this issue for now, we can create a new one or reopen this if someone wants to try making an implementation for MacOS.
