### ISSUE TITLE
Versioning? 

### ISSUE THREAD

**Issue by brokenpip3** [binpash/try#61]
Hi there,

I would like to create an aur package (arch linux users repo) for `try` but I saw that there is no version at all or any git tag.

Do you have in plan to release any version soon?

thanks

ps may I also suggest [bats](https://github.com/bats-core/bats-core) for the testing part?

**Comment by mgree** [comment]
[Done](https://github.com/binpash/try/releases/tag/v0.1.0)! When the package exists, could you please send a PR to our `README.md` to mention it as an installation method?

And: thanks for the testing pointer!

**Comment by brokenpip3** [comment]
Great!

done: https://github.com/binpash/try/pull/64

however I did not included the `man` page because `pandoc` will require too many packages as dependecies only for the build part of the package.
Could you consider to create the man page as part of the ci and store it in the repo? I can create a PR with a GH action for that if you want

Also if you need help with `bats` let me know :)

**Comment by mgree** [comment]
Is it easier for you if the manpage is stored as a GH action artifact or actually in the repo?

(I was planning on copying the prerelease logic from [ffs](https://github.com/mgree/ffs/) and folding in the manpage generation there.)

**Comment by brokenpip3** [comment]
> Is it easier for you if the manpage is stored as a GH action artifact or actually in the repo?

It's the same, as artifact is good :)

>(I was planning on copying the prerelease logic from [ffs](https://github.com/mgree/ffs/) and folding in the manpage generation there.)

omg I love `ffs` now

**Comment by mgree** [comment]
(NB I have not forgotten this, but it likely won't happen until the weekend.)

**Comment by mgree** [comment]
Just kidding, found time this morning. @brokenpip3, please let me know if you want anything else: I'm happy to include the bash completions in the artifact/pre-release; I'm also happy to bump to v0.1.1 if you want a clean release with the right stuff in it.

**Comment by brokenpip3** [comment]
hei @mgree it's the same for me, I can include temporary the man page from the latest version or from a new tag, I let you decide :)

**Comment by mgree** [comment]
Okay---let's do the temporary one from the prerelease/artifact for now. We'll cut a new release when a few of the more interesting WIP PRs land.

**Comment by brokenpip3** [comment]
Fyi the latest [version](https://aur.archlinux.org/packages/try) of the package contains the man page but it's taken from the `latest` one you created last time because the 0.2 tag does not contain the man page as asset: https://github.com/binpash/try/releases/tag/v0.2.0

**Comment by mgree** [comment]
Noted, thank you! I'll be sure to include versioned manpages in the next release.
