### ISSUE TITLE
Code quality/refactor

### ISSUE THREAD

**Issue by mgree** [binpash/try#89]
We should:

 - [x] #103 
 - [x] #108 and #111 and #115 and #116
 - [x] #100
 - [x] #99 (see also #96)
 - [x] #97 (see also #72) 
 - [x] #114 (see also #76)
 - [x] #67 (resolving #45)
 - [x] #117 (see #66 for some initial directions)
 - [X] #105

**Comment by angelhof** [comment]
Great list!

**Comment by a1346054** [comment]
Consider using `shfmt` to unify the codestyle across the scripts, and perhaps enforcing it in CI.

Consider picking some shell styleguide for the project, such as https://google.github.io/styleguide/shellguide.html
